# Clean Leasing Company Google Reviews

Use this starter notebook to load raw data files.

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns", 100)

## Load data

### Businesses and reviews

Read the CSV files. These are [Outscraper](https://outscraper.com/)'s scraped output. They contain Google reviews for leasing companies, apartment complexes, and student housing for three different campustowns.

- Brigham Young University (Provo, UT)
- Penn State University (University Park, PA)
- University of Illinois at Urbana Champaign (Champaign, IL)

## Load and Preprocess Data

### Businesses and Reviews

The main two tables are:

- `df_b`: List of property management companies or apartments
- `df_r`: Google reviews of the property management companies or apartments

In [3]:
df_b = pd.read_csv(
    "https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/results/businesses.csv"
)

df_b.head(3)

,campus,place_id,name,site,category,borough,street,city,postal_code,state,latitude,longitude,verified
0,Brigham Young University,ChIJqyXyo6GQTYcRXGfgeIpqc_I,Alpine Village,https://myalpinevillage.com/,Student housing center,Carterville,1378 Freedom Blvd 200 W,Provo,84604,Utah,40.252607,-111.661247,True
1,Brigham Young University,ChIJGbnTbamQTYcRtZfBrL52jhs,Palladium Apartments,https://www.palladiumprovo.com/,Housing complex,North Park,538 N Freedom Blvd Unit,Provo,84601,Utah,40.240917,-111.661714,True
2,Brigham Young University,ChIJaURIj6GQTYcRCY56AtxjTI4,Glenwood Apartments,https://glenwoodapt.com/,Student housing center,Carterville,1565 N University Ave,Provo,84604,Utah,40.254606,-111.659193,True

In [5]:
df_r = pd.read_csv(
    "https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/results/reviews.csv",
    parse_dates=["review_datetime_utc", "owner_answer_timestamp_datetime_utc"],
)

df_r.head(3)

,place_id,review_id,author_id,author_title,review_text,review_rating,review_img_url,review_datetime_utc,owner_answer,owner_answer_timestamp_datetime_utc,review_likes
0,ChIJqyXyo6GQTYcRXGfgeIpqc_I,ChdDSUhNMG9nS0VJQ0FnSUQ1OXRHZnNnRRAB,100512067005706825621,Laura Brown,Service requests take a very long time to be r...,3,NaN,2023-10-24 12:46:43+00:00,"Dear Laura, \n\n We hear you loud and clear, t...",2023-10-24 14:56:01+00:00,0
1,ChIJqyXyo6GQTYcRXGfgeIpqc_I,ChZDSUhNMG9nS0VJQ0FnSUNwOUstOVpBEAE,102936107836751613731,Pete Haraguchi,I was thinking about giving two stars but I le...,1,https://lh5.googleusercontent.com/p/AF1QipPeIy...,2023-07-29 20:30:26+00:00,"Pete,\n\n Thank you for letting us know about ...",2023-07-29 22:46:48+00:00,12
2,ChIJqyXyo6GQTYcRXGfgeIpqc_I,ChZDSUhNMG9nS0VJQ0FnSURwbGZXTUJ3EAE,103835714740882872235,Jack Radford,DO NOT LIVE HERE. This was the WORST experienc...,1,NaN,2023-08-26 03:31:42+00:00,"Jack, \n\n I’m so sorry — it sounds like we re...",2023-08-26 04:56:04+00:00,3

### Tokens and Sentiments

Read the token list (through spaCy) and sentiment analysis results (using DistilBERT) so that you don't have to run the entire text analysis (which can take over an hour).

- The `df_tokens` file contains lemmatized tokens excluding stop words and punctuation.
- The `df_sentiments` file contains sentiment scores for each review.

In [6]:
df_tokens = pd.read_csv(
    "https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/results/tokens.csv.gz"
)

display(df_tokens.head(3))

                              review_id      text    lemma    explain
0  ChdDSUhNMG9nS0VJQ0FnSUQ1OXRHZnNnRRAB   Service  service       noun
1  ChdDSUhNMG9nS0VJQ0FnSUQ1OXRHZnNnRRAB  requests  request       noun
2  ChdDSUhNMG9nS0VJQ0FnSUQ1OXRHZnNnRRAB      long     long  adjective

In [7]:
df_sentiments = pd.read_csv(
    "https://github.com/bdi475/datasets/raw/main/campustowns-leasing-company-reviews/results/sentiments.csv"
)

display(df_sentiments.head(3))

                              review_id sentiment     score
0  ChdDSUhNMG9nS0VJQ0FnSUQ1OXRHZnNnRRAB  POSITIVE  0.909106
1   ChZDSUhNMG9nS0VJQ0FnSUNwOUstOVpBEAE  NEGATIVE  0.999216
2   ChZDSUhNMG9nS0VJQ0FnSURwbGZXTUJ3EAE  NEGATIVE  0.998690