# Exercise 9 - Line, Scatter, Bar Plots

- 🏆 20 points available

---

▶️ Run the code cell below to import `unittest`, a module used for **🧭 Check Your Work** sections and the autograder.

In [ ]:
import unittest
import base64
import plotly

tc = unittest.TestCase()

---

### 🎯 Exercise 1: Import Packages

#### 👇 Tasks

- ✔️ Import the following Python packages.
  1. `pandas`: Use alias `pd`.
  2. `numpy`: Use alias `np`.
  3. `plotly.express`: Use alias `px`.
  4. `plotly.graph_objects`: Use alias `go`.

In [ ]:
# YOUR CODE BEGINS
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

# YOUR CODE ENDS

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
# DO NOT CHANGE THE CODE IN THIS CELL
_test_case = "part-01"
_points = 2

tc.assertTrue(
    "pd" in globals(), "Check whether you have correctly imported Pandas with an alias."
)
tc.assertTrue(
    "np" in globals(), "Check whether you have correctly imported NumPy with an alias."
)

print(f"The current plotly version is {plotly.__version__}")
plotly_major_version = int(plotly.__version__.split(".")[0])
tc.assertGreaterEqual(
    plotly_major_version, 5, "Your plotly version should be greater than or equal to 5"
)

tc.assertIsNotNone(
    go.Figure,
    "Check whether you have correctly imported plotly.graph_objects with an alias go.",
)
tc.assertIsNotNone(
    px.scatter,
    "Check whether you have correctly imported plotly.express with an alias px.",
)

The current plotly version is 6.3.0

---

### 🎯 Exercise 2: Annual closing gold price 📈

▶️ Run the code cell below to import annual gold closing prices dataset 💛.

In [ ]:
# DO NOT CHANGE THE CODE BELOW
df_gold = pd.read_csv(
    "https://github.com/bdi475/datasets/raw/main/gold-annual-closing-price.csv"
)
df_gold_backup = df_gold.copy()
df_gold.head(5)

   Year  Closing Price
0  1950          34.72
1  1951          34.66
2  1952          34.79
3  1953          34.85
4  1954          35.04

#### 👇 Tasks

- ✔️ Using `df_gold`, create a line chart that displays the closing price by year.
- ✔️ Store your figure to a variable named `fig`.
- ✔️ Add an appropriate title to your figure.
- ✔️ Display the figure using `fig.show()`

In [ ]:
# YOUR CODE BEGINS
fig = px.line(
    df_gold, x="Year", y="Closing Price", title="Annual Closing Price of Gold"
)
fig.show()
# YOUR CODE ENDS

#### 🔑 Sample output

![image](https://github.com/bdi475/images/blob/main/exercises/plotly-dataviz/annual_closing_price_of_gold_line.png?raw=true)

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-02"
_points = 2

tc.assertEqual(len(fig.data), 1, "There must be only one plot in your figure")
tc.assertIsNotNone(fig.layout.title.text, "Missing figure title")
tc.assertEqual(fig.data[0].type, "scatter", "Must be a line chart")
tc.assertIsNotNone(fig.data[0].line.color, "Must be a line chart")
np.testing.assert_array_equal(fig.data[0].x, df_gold["Year"], "Incorrect x-axis data")
np.testing.assert_array_equal(
    fig.data[0].y, df_gold["Closing Price"], "Incorrect y-axis data"
)

---

### 🎯 Exercise 3: Annual closing gold price in 2000s 📈

#### 👇 Tasks

- ✔️ Using `df_gold`, create a line chart that displays the closing price by year.
  - Only include years 2000 or later (`df_gold['Year'] >= 2000`).
- ✔️ Store your figure to a variable named `fig`.
- ✔️ Add an appropriate title to your figure.
- ✔️ Display the figure using `fig.show()`

#### 🚀 Hints

- 👉 `fig = px.line(df_gold[df_gold['Year'] >= 2000], x='Year', ...)`

In [ ]:
# YOUR CODE BEGINS
fig = px.line(
    df_gold[df_gold["Year"] >= 2000],
    x="Year",
    y="Closing Price",
    title="Annual Closing Price of Gold",
)
fig.show()
# YOUR CODE ENDS

#### 🔑 Sample output

![image](https://github.com/bdi475/images/blob/main/exercises/plotly-dataviz/annual_closing_price_of_gold_in_2000s_line.png?raw=true)

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-03"
_points = 2

tc.assertEqual(len(fig.data), 1, "There must be only one plot in your figure")
tc.assertIsNotNone(fig.layout.title.text, "Missing figure title")
tc.assertEqual(fig.data[0].type, "scatter", "Must be a line chart")
tc.assertIsNotNone(fig.data[0].line.color, "Must be a line chart")
np.testing.assert_array_equal(
    fig.data[0].x,
    df_gold_backup.query(base64.b64decode(b"WWVhciA+PSAyMDAw").decode())["Year"],
    "Incorrect x-axis data",
)
np.testing.assert_array_equal(
    fig.data[0].y,
    df_gold_backup.query(base64.b64decode(b"WWVhciA+PSAyMDAw").decode())[
        "Closing Price"
    ],
    "Incorrect y-axis data",
)

---

### 📌 Import dataset

![BLUEbikes](https://github.com/bdi475/images/blob/main/lecture-notes/dataviz-python/bluebike-transparent-bike.png?raw=true)

From this point on, you will work with bikesharing trips dataset 🚲. The original dataset has been retrieved from [https://www.bluebikes.com/system-data](https://www.bluebikes.com/system-data).

▶️ Run the code below to import the dataset. This dataset is a fairly large with 200k rows, **so it may take up to a few minutes**.

In [ ]:
# Display all columns
pd.set_option("display.max_columns", 50)

df_trips = pd.read_csv(
    "https://github.com/bdi475/datasets/blob/main/bluebikes-trip-data-2020-sampled.csv.gz?raw=true",
    compression="gzip",
    parse_dates=["start_time", "stop_time"],
)

df_trips_backup = df_trips.copy()

display(df_trips)

,trip_duration,start_station_name,end_station_name,user_type,start_time,stop_time
0,344,175 N Harvard St,Harvard Kennedy School at Bennett St / Eliot St,Customer,2020-08-06 16:52:57,2020-08-06 16:58:42
1,451,Harvard University River Houses at DeWolfe St ...,175 N Harvard St,Subscriber,2020-08-04 10:43:49,2020-08-04 10:51:21
2,750,Prudential Center - 101 Huntington Ave,Central Sq Post Office / Cambridge City Hall a...,Subscriber,2020-01-19 18:44:08,2020-01-19 18:56:38
3,1422,Cambridge St - at Columbia St / Webster Ave,Mass Ave T Station,Customer,2020-08-15 18:11:50,2020-08-15 18:35:32
4,3405,Mattapan T Stop,Mattapan T Stop,Subscriber,2020-01-11 12:51:52,2020-01-11 13:48:37
...,...,...,...,...,...,...
199995,255,MIT Vassar St,MIT Stata Center at Vassar St / Main St,Subscriber,2020-03-04 15:54:25,2020-03-04 15:58:41
199996,1451,Farragut Rd at E. 6th St,Aquarium T Stop - 200 Atlantic Ave,Subscriber,2020-07-07 20:20:51,2020-07-07 20:45:03
199997,454,Harvard Square at Mass Ave/ Dunster,Lesley University,Subscriber,2020-09-21 15:33:06,2020-09-21 15:40:41
199998,322,Harvard Law School at Mass Ave / Jarvis St,Verizon Innovation Hub 10 Ware Street,Subscriber,2020-02-05 17:07:50,2020-02-05 17:13:13
199999,3291,Back Bay T Stop - Dartmouth St at Stuart St,Boylston St at Exeter St,Customer,2020-09-03 16:30:55,2020-09-03 17:25:47

---

### 🎯 Exercise 4: Create an aggregated DataFrame with number of trips by date

#### 👇 Tasks

- ✔️ One of the common tasks when visualizing your data is to aggregate your data before plotting them.
- ✔️ Using `df_trips`, create a new DataFrame named `df_num_trips_by_date` that holds the number of trips by date.
- ✔️ We will give you the fully working code below.

![Code](https://github.com/bdi475/images/blob/3e25d254f4d5f9c13c82cadd7f1c999a82e37d15/lecture-notes/dataviz-python/carbon-groupby-num-trips-by-date-01.png?raw=true)

In [ ]:
# YOUR CODE BEGINS
df_num_trips_by_date = df_trips.groupby(
    df_trips["start_time"].dt.date, as_index=False
).size()

df_num_trips_by_date.rename(
    columns={"start_time": "date", "size": "num_trips"}, inplace=True
)

display(df_num_trips_by_date)
# YOUR CODE ENDS

           date  num_trips
0    2020-01-01        156
1    2020-01-02        364
2    2020-01-03        421
3    2020-01-04        160
4    2020-01-05        214
..          ...        ...
330  2020-11-26        153
331  2020-11-27        411
332  2020-11-28        429
333  2020-11-29        443
334  2020-11-30        201

[335 rows x 2 columns]

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-04"
_points = 2

df_check = (
    df_trips_backup.groupby(df_trips_backup["start_time"].dt.date)
    .size()
    .reset_index()
    .rename(columns={"start_time": "date", 0: "num_trips"})
)

pd.testing.assert_frame_equal(
    df_num_trips_by_date.sort_values("date").reset_index(drop=True),
    df_check.sort_values("date").reset_index(drop=True),
)

---

### 🎯 Exercise 5: Number of trips by date (📈 Line Chart)

#### 👇 Tasks

- ✔️ Using `df_num_trips_by_date`, create a **line** chart that displays the number of trips by date.
- ✔️ Store your figure to a variable named `fig`.
- ✔️ Add an appropriate title to your figure.
- ✔️ Display the figure using `fig.show()`

In [ ]:
# YOUR CODE BEGINS
fig = px.line(
    df_num_trips_by_date,
    x="date",
    y="num_trips",
    title="Number of Trips by Date in 2020",
)
fig.show()
# YOUR CODE ENDS

#### 🔑 Sample output

![image](https://github.com/bdi475/images/blob/main/exercises/plotly-dataviz/number_of_trips_by_date_line.png?raw=true)

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-05"
_points = 2

tc.assertEqual(len(fig.data), 1, "There must be only one plot in your figure")
tc.assertIsNotNone(fig.layout.title.text, "Missing figure title")
tc.assertEqual(fig.data[0].type, "scatter", "Must be a line chart")
tc.assertIsNotNone(fig.data[0].line.color, "Must be a line chart")
np.testing.assert_array_equal(
    fig.data[0].x, df_num_trips_by_date["date"], "Incorrect x-axis data"
)
np.testing.assert_array_equal(
    fig.data[0].y, df_num_trips_by_date["num_trips"], "Incorrect y-axis data"
)

---

### 🎯 Exercise 6: Number of trips by date (Scatter Plot)

#### 👇 Tasks

- ✔️ Using `df_num_trips_by_date`, create a **scatter** plot that displays the number of trips by date.
- ✔️ Store your figure to a variable named `fig`.
- ✔️ Add an appropriate title to your figure.
- ✔️ Display the figure using `fig.show()`

In [ ]:
# YOUR CODE BEGINS
fig = px.scatter(
    df_num_trips_by_date,
    x="date",
    y="num_trips",
    title="Number of Trips by Date in 2020",
)
fig.show()
# YOUR CODE ENDS

#### 🔑 Sample output

![image](https://github.com/bdi475/images/blob/main/exercises/plotly-dataviz/number_of_trips_by_date_scatter.png?raw=true)

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-06"
_points = 2

tc.assertEqual(len(fig.data), 1, "There must be only one plot in your figure")
tc.assertIsNotNone(fig.layout.title.text, "Missing figure title")
tc.assertEqual(fig.data[0].type, "scatter", "Must be a scatter plot")
tc.assertIsNone(fig.data[0].line.color, "Must be a scatter plot")
np.testing.assert_array_equal(
    fig.data[0].x, df_num_trips_by_date["date"], "Incorrect x-axis data"
)
np.testing.assert_array_equal(
    fig.data[0].y, df_num_trips_by_date["num_trips"], "Incorrect y-axis data"
)

---

### 🎯 Exercise 7: Number of trips by week of the year at the top 3 stations

▶️ Run the code below to find the top 3 stations (by start position).

In [ ]:
top3_start_stations = df_trips["start_station_name"].value_counts().index[:3]
top3_start_stations

Index(['Central Square at Mass Ave / Essex St',
       'Charles Circle - Charles St at Cambridge St',
       'MIT at Mass Ave / Amherst St'],
      dtype='object', name='start_station_name')

#### 👇 Tasks

- ✔️ Using `df_trips` and `top3_start_stations`, create a new DataFrame named `df_num_trips_from_station` that holds the number of trips by week of the year at the top 3 stations.
- ✔️ We will give you the fully working code below.

![Code](https://github.com/bdi475/images/blob/main/lecture-notes/dataviz-python/carbon-groupby-week-and-start-station-01.png?raw=true)

In [ ]:
# YOUR CODE BEGINS
df_trips_from_top3_stations = df_trips[
    df_trips["start_station_name"].isin(top3_start_stations)
]

df_num_trips_from_station = df_trips_from_top3_stations.groupby(
    [
        df_trips_from_top3_stations["start_time"].dt.isocalendar().week,
        "start_station_name",
    ],
    as_index=False,
).size()

df_num_trips_from_station.rename(
    columns={"start_time": "date", "size": "num_trips"}, inplace=True
)

display(df_num_trips_from_station)
# YOUR CODE ENDS

     week                           start_station_name  num_trips
0       1        Central Square at Mass Ave / Essex St         41
1       1  Charles Circle - Charles St at Cambridge St         10
2       1                 MIT at Mass Ave / Amherst St         25
3       2        Central Square at Mass Ave / Essex St         80
4       2  Charles Circle - Charles St at Cambridge St         45
..    ...                                          ...        ...
141    48        Central Square at Mass Ave / Essex St         52
142    48  Charles Circle - Charles St at Cambridge St         48
143    48                 MIT at Mass Ave / Amherst St         29
144    49        Central Square at Mass Ave / Essex St          3
145    49  Charles Circle - Charles St at Cambridge St          4

[146 rows x 3 columns]

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-07"
_points = 2

df_t3 = df_trips_backup[
    df_trips_backup["start_station_name"].isin(
        df_trips_backup["start_station_name"].value_counts().index[:3]
    )
]

df_check = (
    df_t3.groupby([df_t3["start_time"].dt.isocalendar().week, "start_station_name"])
    .size()
    .reset_index()
    .rename(columns={"start_time": "date", 0: "num_trips"})
)

pd.testing.assert_frame_equal(
    df_num_trips_from_station.sort_values(["week", "start_station_name"]).reset_index(
        drop=True
    ),
    df_check.sort_values(["week", "start_station_name"]).reset_index(drop=True),
)

---

### 🎯 Exercise 8: Number of trips by week of the year at the top 3 stations (Line Chart)

#### 👇 Tasks

- ✔️ Using `df_num_trips_from_station`, create a **line** chart that displays the number of trips by week.
- ✔️ Draw three line charts on a single figure.
  - Use different colors to distinguish `start_station_name`.
- ✔️ Store your figure to a variable named `fig`.
- ✔️ Add an appropriate title to your figure.
- ✔️ Display the figure using `fig.show()`

In [ ]:
# YOUR CODE BEGINS
fig = px.line(
    df_num_trips_from_station,
    x="week",
    y="num_trips",
    color="start_station_name",
    title="Number of Trips by Week of the Year for Top 3 Stations",
)
fig.show()
# YOUR CODE ENDS

#### 🔑 Sample output

![Expected Output](https://github.com/bdi475/images/blob/main/lecture-notes/dataviz-python/expected-output-num-trips-by-week-top3-stations.png?raw=true)

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-08"
_points = 2

tc.assertEqual(len(fig.data), 3, "There must be three plots in your figure")
tc.assertIsNotNone(fig.layout.title.text, "Missing figure title")

for i in range(3):
    tc.assertEqual(fig.data[i].type, "scatter", "Must be a line plot")
    tc.assertIsNotNone(fig.data[i].line.color, "Must be a line plot")

    np.testing.assert_array_equal(
        fig.data[i].x,
        df_num_trips_from_station[
            df_num_trips_from_station["start_station_name"]
            == df_num_trips_from_station["start_station_name"].unique()[i]
        ]["week"],
        "Incorrect x-axis data",
    )
    np.testing.assert_array_equal(
        fig.data[i].y,
        df_num_trips_from_station[
            df_num_trips_from_station["start_station_name"]
            == df_num_trips_from_station["start_station_name"].unique()[i]
        ]["num_trips"],
        "Incorrect y-axis data",
    )

---

### 🎯 Exercise 9: Create an aggregated DataFrame with number of trips by station

#### 👇 Tasks

- ✔️ Using `df_trips`, create a new DataFrame named `df_num_trips_by_month` that holds the number of trips by start station names.
- ✔️ Only select the top 10 stations (by number of trips).
- ✔️ We will give you the fully working code below.

![Code](https://github.com/bdi475/images/blob/main/lecture-notes/dataviz-python/carbon-num-trips-by-station-01.png?raw=true)

In [ ]:
# YOUR CODE BEGINS
df_num_trips_from = (
    df_trips["start_station_name"]
    .value_counts()
    .iloc[:10]
    .to_frame()
    .reset_index()
    .rename(columns={"start_station_name": "start_station", "count": "num_trips"})
)

display(df_num_trips_from)
# YOUR CODE ENDS

                                       start_station  num_trips
0              Central Square at Mass Ave / Essex St       3398
1        Charles Circle - Charles St at Cambridge St       3172
2                       MIT at Mass Ave / Amherst St       2871
3  Christian Science Plaza - Massachusetts Ave at...       2614
4                                 Ames St at Main St       2331
5                    MIT Pacific St at Purrington St       2255
6                             Cross St at Hanover St       2183
7                           Boylston St at Jersey St       2139
8                     Beacon St at Massachusetts Ave       2121
9                Harvard Square at Mass Ave/ Dunster       2019

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-09"
_points = 2

df_check = (
    df_trips_backup.groupby("start_station_name")
    .size()
    .sort_values(ascending=False)
    .iloc[:10]
    .reset_index()
    .rename(columns={"start_station_name": "start_station", 0: "num_trips"})
)

pd.testing.assert_frame_equal(
    df_num_trips_from.reset_index(drop=True), df_check.reset_index(drop=True)
)

---

### 🎯 Exercise 10: Number of trips by station (Bar Chart)

#### 👇 Tasks

- ✔️ Using `df_num_trips_from`, create a **bar** chart that displays the number of trips by station.
- ✔️ Store your figure to a variable named `fig`.
- ✔️ Add an appropriate title to your figure.
- ✔️ Display the figure using `fig.show()`

In [ ]:
# YOUR CODE BEGINS
fig = px.bar(
    df_num_trips_from,
    x="start_station",
    y="num_trips",
    title="Number of Trips by Start Station",
)
fig.show()
# YOUR CODE ENDS

#### 🔑 Sample output

![Expected Output](https://github.com/bdi475/images/blob/main/lecture-notes/dataviz-python/expected-output-num-trips-by-station-bar-chart.png?raw=true)

#### 🧭 Check Your Work

Run the code cell below to test your solution.

- ✔️ If the code cell runs without errors, you're good to move on.
- ❌ If the code cell produces an error, review your code and fix any mistakes.

In [ ]:
_test_case = "part-10"
_points = 2

tc.assertEqual(len(fig.data), 1, "There must be only one plot in your figure")
tc.assertIsNotNone(fig.layout.title.text, "Missing figure title")
tc.assertEqual(fig.data[0].type, "bar", "Must be a bar chart")
tc.assertEqual(
    fig.data[0].orientation, "v", "Your plot should have a vertical orientation"
)
np.testing.assert_array_equal(
    fig.data[0].x, df_num_trips_from["start_station"], "Incorrect x-axis data"
)
np.testing.assert_array_equal(
    fig.data[0].y, df_num_trips_from["num_trips"], "Incorrect y-axis data"
)